- interface/backend/submission.py
- interface/settings.py
- interface/templates/interface/submission_list.html
- interface/urls.py
- interface/views.py
> Ldap settings

- README.md
- deploy/interface.nomad
- interface/admin.py
- interface/backend/minio_api.py
- interface/backend/submission.py
- interface/models.py
- interface/settings.py
- interface/templates/interface/submission_list.html
- interface/utils.py
- interface/views.py
> Quick fixes

- interface/models.py
- interface/utils.py
Still some flake8 errors from the previous PR.
> Fix coding style

- interface/models.py
- interface/views.py
Send token as a GET parameter in the callback_url.
> Send the token in the link

- interface/models.py
https://github.com/vmck/acs-interface/issues/17
> Set the `restrict_network` flag

- interface/templates/interface/homepage.html
- interface/templates/interface/login.html
- interface/templates/interface/submission_list.html
- interface/templates/interface/submission_result.html
- interface/templates/interface/tracker.html
- interface/templates/interface/upload.html
Track users with google analytics. Ping @mgax for access.
Should we [track the user id](https://davidsimpson.me/2013/10/17/identifying-your-users-in-google-analytics-while-complying-with-section-7-of-the-terms-of-service/)?
> Track every page

- interface/settings.py
fixes https://github.com/vmck/acs-interface/issues/74
> check if ldap is configured

- interface/templates/interface/review_modal.html
> Fix xss #56

- interface/admin.py
- interface/backend/minio_api.py
Fixes https://github.com/vmck/acs-interface/issues/104
> Skip missing files but report the error

- interface/models.py
Fix the uploads. It's broken in production right now.
> `self.timestamp` is null for new records

- interface/templates/interface/submission_result.html
- interface/views.py
Fixes #95 
Remove the field with the stderr output.
This PR should be merged alongside [this](https://github.com/vmck/vagrant-vmck/pull/41)
> Remove the error filed

- Readme.md
Instructions to add a new homework for a specific course.
Fixes https://github.com/vmck/acs-interface/issues/125
> Add instructions to add new homework

- Dockerfile
- ci/provision-acs-interface.sh
- interface/templates/interface/submission_result.html
- interface/views.py
Solves #65 - currently it adds only the quote.
Should we add a 25% chance to show an issue from this repo (```acs-interface```)?
[How it look](https://ibb.co/v3LgMHp)
> Add fortune teller while homework is being tested

- interface/templates/interface/submission_list.html
Fixes #123 
Add ```Reviewed``` column for the status field - it would check if there is any review message in the ```review``` field for a submission.
> Review status

- Pipfile.lock
> Django version 3.0 and others

- interface/views.py
Fixes #135.
After making an upload redirect to the course assignment where the student uploaded the homework.
> Add redirect to course assignment

- Vagrantfile
- ci/provision-acs-interface.sh
- ci/provision-cluster.sh
- ci/provision-system.sh
- ci/provision-vmck.sh
Fixes https://github.com/vmck/acs-interface/issues/114
> Provision as root so that docker works first time

- Dockerfile
- runinterface
* Clean up debian package cache
* Install pipenv globally
* Copy source code after installing packages
> Clean up the dockerfile

- interface/actions_logger.py
Fixes #147. 
Return the result from the decorator.
> Fix logging decorator

- interface/templates/interface/submission_list.html
- interface/templates/interface/users_list.html
Fixes #151 .
Move the review status button to the assignment page.
> Move review status to another view

- interface/views.py
Fixes #152.
After uploading redirect a user to his submission page for that specific assignment.
> Correct redirect and sort after timestamp

- interface/admin.py
> Search field for users

- interface/admin.py
- interface/backend/submission.py
- interface/management/commands/sync_vmck.py
- interface/models.py
- interface/moss.py
- interface/settings.py
- interface/views.py
- runinterface
Check for submissions status in an asynchronous way + add debugger logs
> Asynchronous check for submission status

- interface/models.py
Quick fix for a bug inserted in this [PR](https://github.com/vmck/acs-interface/pull/177)
> Quick fix async None

- interface/backend/submission.py
- interface/templates/interface/upload.html
- interface/views.py
Fixes #184. It's simply checks if the file is an actual zip and if it is not corrupt. Django takes care that the user actually uploads a non-empty archive.
> No empty sub

- interface/admin.py
Fixes #196.
Filter when getting a new form for adding a new assignment.
**LE**:
* The tests will be added in #210
> Add filter for teaching assistants

- testsuite/test_submission_actions.py
Addresses naming issue from #213.
> Fix naming

- interface/templates/interface/generics/review_modal.html
The review button redirects to a bad url.
> Fix broken review button

- interface/admin.py
- interface/models.py
- testsuite/conftest.py
- testsuite/test_student_workflow.py
- testsuite/test_ta_workflow.py
Fixes #210 
Add tests for the teaching assistants' workflows.
> Teaching assistants tests

- interface/backend/submission/submission_scheduler.py
- interface/models.py
- interface/settings.py
> Automatically starting threads

- interface/forms.py
- interface/settings.py
- interface/uploadhandler.py
- interface/views.py
- testsuite/test_student_workflow.py
> Limit filesize for upload

- Readme.md
- ci/fixtures.json
- testsuite/stress/locust.py
- testsuite/test_student_workflow.py
Fixes #236
Stress tests using [Locust](https://locust.io/)
> Init Locust stress test

- interface/admin.py
- interface/models.py
- interface/views.py
- testsuite/test_minio.py
- testsuite/test_ta_workflow.py
> Replace temporary directory with buffer for download

- CONTRIB.md
> Add CONTRIB.md

- CONTRIB.md
- interface/backend/submission/evaluator/vmck.py
- interface/models.py
- testsuite/test_internals.py
- Introduce a new state error for a submission.
- If the json is not valid during the submission update, the method will now return the new state.
Fixes https://github.com/vmck/acs-interface/issues/265
- Validated through the /test_internals.py class
> New state ERROR for submission update method

- CONTRIB.md
- interface/models.py
- interface/utils.py
- interface/views.py
- testsuite/test_views.py
Replaces `asserts` statements and instead raises exceptions. I only found one assertion that is not inside the `testsuite` folder.
Follow up: should I create a custom `JwtException` class? I didn't do it since its just one...
Fixes #263
-
> Replace asserts

- .drone.yml
- .github/workflows/linter.yml
- interface/actions_logger.py
- interface/admin.py
- interface/backend/submission/evaluator/vmck.py
- interface/backend/submission/submission.py
- interface/management/commands/waitress.py
- interface/models.py
- interface/moss.py
- interface/scoring.py
- interface/settings.py
- interface/uploadhandler.py
- interface/views.py
- testsuite/conftest.py
- testsuite/test_penalty.py
- testsuite/test_student_workflow.py
- testsuite/test_submission_actions.py
- testsuite/test_ta_workflow.py
- testsuite/test_views.py
Have the linting on github actions
Fixes #271 (link the issue)
Github actions
> GitHub actions

- interface/backend/submission/submission_scheduler.py
- interface/models.py
Add more logs
- The tests should pass
> Add more logs

- interface/backend/submission/submission_scheduler.py
- interface/models.py
Keep submissions in memory
- Tests are passing
> Keep sub in memory

- .github/workflows/ci.yml
- interface/models.py
- interface/templates/interface/generics/base.html
- interface/templates/interface/homepage.html
- interface/views.py
- testsuite/test_views.py
> Jw refactor homepage

- interface/templates/interface/subs_for_user.html
- interface/views.py
Username of user that assigned homework appears on top instead of current logged user
Fixes #298
- What was used for testing this PR
> fixed user assignment bug
